### ISSUE TITLE
Git fetch command fails, is there any way to improve it?

### ISSUE THREAD

**Issue by dadayama** [ArtiomTr/jest-coverage-report-action#11]
Hi.

I have been able to use this action to run tests successfully, but the git fetch command fails.
I think it's because I don't specify the remote branch name.
Is there any way to work around this?

```
Test execution failed with message: "The process '/usr/local/bin/npx' failed with exit code 1"
/usr/bin/git fetch develop --depth=1
fatal: 'develop' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Fetch failed The process '/usr/bin/git' failed with exit code 128
/usr/bin/git checkout -f develop
error: pathspec 'develop' did not match any file(s) known to git.
Error: The process '/usr/bin/git' failed with exit code 1
```

If there is no workaround at this point, I would appreciate it if you could fix it.
Or can I submit a pull request?

Thanks.

**Comment by ArtiomTr** [comment]
Hello! Thank you for your issue.

It seems to be action's bug, because as I see, jest-coverage-report-action passes branch name into `git fetch` command ([here](https://github.com/ArtiomTr/jest-coverage-report-action/blob/master/src/collect/getRawCoverage.ts#L13)), but `git fetch` command requires repository ([git documentation](https://git-scm.com/docs/git-fetch))

At the moment, there is no workaround for this.

If you want to fix this problem, I'd love to see a PR from you!

**Comment by dadayama** [comment]
Thanks for your reply!

So I would like to fix this on my end, but I'm still pondering about the design.
How about passing an argument like the following?

```
// action.yml
...
inputs:
    remote_repository_name:
        required: false
        default: origin
...
```

```
// index.ts
const [token, testScript, coverageThresholdStr, remoteRepositoryName] = argv.slice(2);
...
const baseReport = await collectCoverage(
  testScript,
  `${remoteRepositoryName} {pull_request.base.ref}`
);
```

**Comment by dadayama** [comment]
We believe that we need to test this action before we issue a PR.
While I'm checking, can I upload the forked repository to the marketplace to see if it works?

**Comment by ArtiomTr** [comment]
I see that in `git fetch` documentation there is a flag `--all` to fetch all remotes. So the usage will be:

```bash
git fetch --all
```

In that case, user could have multiple remotes and action will fetch all information from them. And, with that solution, we don't need additional parameter.

What do you think of this solution?

**Comment by ArtiomTr** [comment]
https://github.com/ArtiomTr/jest-coverage-report-action/issues/11#issuecomment-801840500
Yes, of course, but wouldn't it be easier for you to test using [{owner}/{repo}/{path}@{ref} syntax?](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses)

**Comment by dadayama** [comment]
https://github.com/ArtiomTr/jest-coverage-report-action/issues/11#issuecomment-801841845
> `git fetch --all`

Thanks for the suggestion!
This solution is simple and good.

Also, the testing method you suggested seems to work well.
I'll submit a PR after trying it this way!

**Comment by dadayama** [comment]
The solution you just suggested worked fine.
Thank you!

However, it fails with `npm ci`.
There should be a package-lock.json in the repository where I'm running the tests, but I'm getting angry that I don't have it.
Can you think of any way to handle this?

```
/usr/local/bin/npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2021-03-18T13_06_11_341Z-debug.log
Error: The process '/usr/local/bin/npm' failed with exit code 1
```

By the way, the following tasks are working, so it looks like I didn't forget to commit anything.

```
- run: cat ${{ github.workspace }}/package-lock.json
```

**Comment by ArtiomTr** [comment]
> npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

It looks like you're using old npm version, which generates 1st `package-lock.json` version. As I understand, github action uses latest npm, which creates and uses 2nd `package-lock.json` version. Because of that, `npm ci` not working

As I understood, `git fetch` issue is not related to `npm ci`, so I will create a separate one.

So, could you please create a PR so I can review the code and merge it?

**Comment by dadayama** [comment]
It would certainly be better to work on it as a separate issue.
I've confirmed that the `git fetch` process worked in my local environment, so I'll submit a PR for this issue first.
