### ISSUE TITLE
Head coverage is not compared to the base coverage when `skip-step` set to `all`

### ISSUE THREAD

**Issue by ArtiomTr** [ArtiomTr/jest-coverage-report-action#111]
### Discussed in https://github.com/ArtiomTr/jest-coverage-report-action/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **adesurirey** July  5, 2021</sup>
> Comparing coverage with base branch.

Looks great, how do I activate this? 

I'm currently using `v2.0-rc.2` which works great but I do not have this kind of reports on my PR as on the README screenshot. </div>

**Comment by adesurirey** [comment]
@ArtiomTr may I help on this one?

**Comment by ArtiomTr** [comment]
@adesurirey, thanks for the suggestion, but unfortunately I have already started working on this. To fix this issue, I need to complete a lot of smaller tasks. In order for you to be able to follow the progress of the work, I created a draft PR (#118). The latest information on the progress of work will appear there.
