### ISSUE TITLE
Request: display base branch values as tooltip

### ISSUE THREAD

**Issue by oxc** [ArtiomTr/jest-coverage-report-action#112]
In the PR reports, it would be nice to see the exact base branch values as tooltips when hovering over the head branch values.

Howering over the percentage would show the percentage from the base branch run, etc.

**Comment by ArtiomTr** [comment]
Hey @oxc,

Thank you for your suggestion! I'll try to implement this feature as soon as possible

**Comment by ArtiomTr** [comment]
Feature was implemented in #118 PR and will be available in next release
