### ISSUE TITLE
Make coverage annotation optional

### ISSUE THREAD

**Issue by sidharthv96** [ArtiomTr/jest-coverage-report-action#131]
Coverage annotations in the PR makes reviewing extremely difficult. 
If there was an option to disable the annotation, that would be very helpful.

**Comment by sidharthv96** [comment]
Checked the code, found `annotations: 'failed-tests'`.
It's missing in the docs.

**Comment by ArtiomTr** [comment]
@sidharthv96, annotations appeared in `2.0` version, which is currently not released officially, only pre-releases. The `2.x` version's docs are [here](https://www.covbot.dev/configuration)
