### ISSUE TITLE
proposal: use combination of action inputs to identify existing PR comment

### ISSUE THREAD

**Issue by BohdanPetryshyn** [ArtiomTr/jest-coverage-report-action#146]
### Problem
Having multiple Jest tests in a single working directory is a pretty common situation. For example, a project might have unit and integration tests implemented with Jest. It sounds reasonable to separate coverage of unit and integration tests. However, since the action uses only a working directory to identify an existing comment [here](https://github.com/ArtiomTr/jest-coverage-report-action/blob/09be8eae8c09dc2dd43b43e27cff33dc002349db/src/constants/getReportTag.ts#L1), the results of multiple tests end up written to a single comment.

#### Example

Given two steps that both use the action with same working directory, but different test scripts:

<img width="733" alt="Screenshot 2021-09-16 at 14 42 11" src="https://user-images.githubusercontent.com/45905756/133606168-6af4425d-480b-4263-83a7-aeb60827d9f2.png">

The workflow results in two simultaneous updates to the same comment:

![image](https://user-images.githubusercontent.com/45905756/133606447-19082a6f-425c-4df6-a9ed-3a5c91c18b8c.png)

### Solution
I suggest including other action inputs to the `reportTag` such as:
* `test-script`;
* `coverage-file`;
* `base-coverage-file`.

The user will later be able to set the `custom-title` to make the reports easier to distinguish.

This is a very naive solution to the problem. I'm just quickly filing the issue while working on my main project. I'll be happy to discuss other solutions and implement one later on the weekends.

**Comment by BohdanPetryshyn** [comment]
Hi @ArtiomTr! Tagging you here in case you didn't receive a new issue notification 🔔

**Comment by ArtiomTr** [comment]
Hello @BohdanPetryshyn 👋

Sorry for the late reply. Your suggestion sounds reasonable and helpful. I think this behavior can be achieved simply by adding a test script to the tag - different test scripts will have different outputs. Alternatively, we can put a hash of the options object in the tag - this would allow the action to correctly identify the coverage comment for different option combinations. However, this solution might be too overwhelming for your issue, so I don't know which solution is better. 

I would be glad if you could implement one of these solutions. If you'll choose second solution to implement, don't forget to throw out sensitive information - token.

I hope I answered your questions. Feel free to discuss possible solutions or just open a PR if you want to participate in the development of this tool. Thank you for your initiative!

**Comment by BohdanPetryshyn** [comment]
Thank you for your response, @ArtiomTr! I will open a PR later this week

**Comment by BohdanPetryshyn** [comment]
Working on this 👨‍💻
