### ISSUE TITLE
Output total coverage table

### ISSUE THREAD

**Issue by Couto** [ArtiomTr/jest-coverage-report-action#176]
### Idea

Take advantage of the `outputs` feature from Github Actions to return the table that display the Total Coverage

### Description

Expose in the outputs property, the markdown table (and/or other variations) so that we can display the coverage results in different actions/locations. e.g:

Use cases:
 - Display the total coverage in the release page
 - Update Jira (or other PM software) issues with the coverage for that story

### Alternatives

- Current alternative is, if possible, find the comment posted by this action, (using a find comment action) and copy the content.
- Manually find the table and copy/paste into the desired location

**Comment by MishaKav** [comment]
I find the solution in a similar package
https://github.com/marketplace/actions/jest-coverage-comment
