### ISSUE TITLE
Allow skipping switch to base branch

### ISSUE THREAD

**Issue by oxc** [ArtiomTr/jest-coverage-report-action#199]
### Idea

I would like to skip the switching to the base branch, especially if I have supplied both coverage files already.

### Description

When the action is run on a PR, it always switches to the base branch. This happens regardless of whether skip-step is set to all, or whether coverage-file and base-coverage-file have been supplied.

I would like to skip this step, especially in this scenario. I would also like to be able to skip it, even if I don't have coverage from the base-branch available, and only provide the coverage-file.

This allows me to use reports generated by other test runs, without having to fetch all the git history for switching.

Furthermore, the checkout is left on the base branch (at least in some cases?), which can be confusing to following actions (e.g. uploads of coverage data to remote services).

**Comment by ArtiomTr** [comment]
Hey @oxc :wave:,

Your idea sounds interesting! I would try to implement this.
Regarding the behavior that branch remaining switched after the action is completed: as I understand it, you would like to see a return to the original branch after it is executed?

**Comment by oxc** [comment]
Hi @ArtiomTr, cool! 😊 Yes, I believe this would be the behavior I would find least unexpected.

**Comment by diestrin** [comment]
Yes, it is weird that after running this action, other steps are left with the base branch file system, +1 to switch back to the original branch

**Comment by dstoyanoff** [comment]
One more vote from me to switch back to the original branch. Now we need to do that manually :(

**Comment by ArtiomTr** [comment]
Hello everyone,

Sorry for late response. The bug is fixed and now is available under `v2` flag.
