### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by bluelovers** [ArtiomTr/jest-coverage-report-action#200]
### Describe a bug

https://github.com/bluelovers/ws-mtg/runs/4304838780?check_suite_focus=true

```
SyntaxError: Invalid regular expression: /**/node_modules//: Nothing to repeat
```

### Expected behavior

should run test without error like running on local test

### Details

-   Action version:
-   OS, where your action is running (windows, linux):
-   <details><summary>action.yml file</summary>

        ```yml
        # Insert your action.yml file here. Don't forget to remove all sensitive information (e.g. tokens)
        ```

    </details>

-   <details><summary>Screenshots</summary>

        

        

    </details>

**Comment by ArtiomTr** [comment]
Hello @bluelovers :wave:,

Looks like the problem is with your tests or jest configuration. Could you please check if the report.json file is generated when you run your test command?
