### ISSUE TITLE
The dist files for v1.1 are still from v1.0

### ISSUE THREAD

**Issue by jgillick** [ArtiomTr/jest-coverage-report-action#22]
The bundled/built `dist/index.js` file still still attempts to `git fetch ${branch} --depth=1` and `npm ci` in `getRawCoverage.ts`.

However, it looks like dist is up-to-date in master. So the tag just needs to be moved, or create a new `v1.1.1` tag.

## To move the tag

```
git tag --force v1.1
git push --force --tags
```

**Comment by ArtiomTr** [comment]
Thank you for your issue!

New version [v1.2](https://github.com/ArtiomTr/jest-coverage-report-action/releases/tag/v1.2) is released
