### ISSUE TITLE
Parse threshold information from jest configuration in 'package.json'

### ISSUE THREAD

**Issue by ArtiomTr** [ArtiomTr/jest-coverage-report-action#228]
### Idea

Action should parse threshold information not only from `jest.config.*` files, but also from `package.json`.

### Description

The schema of jest configuration in `package.json` file is described [here](https://jestjs.io/docs/configuration)

### Additional context

Originally described in #223 issue.

**Comment by tobiasbueschel** [comment]
This would be great to have @ArtiomTr - adding to it, maybe there's a way to configure the path to the `jest.config.*` file so that one can also use this action on multiple within a npm workspace monorepo setup?

Thanks for all your work with this! Cheers

**Comment by grahammcculloch** [comment]
I'm glad this has been suggested as it's a problem I'm encountering. Specifically, in my case, the config in `package.json` is for a Create React App:
```json
{
  "jest": {
    "watchPathIgnorePatterns": [
      "<rootDir>\\/src\\/(.+\\/)+.+\\.stories\\.tsx"
    ],
    "collectCoverageFrom": [
      "<rootDir>/src/pages/**/*.+(ts|tsx|js)",
      "<rootDir>/src/components/**/*.+(ts|tsx|js)",
      "!<rootDir>/src/**/*.style.+(tsx)",
      "!<rootDir>/src/**/*.stories.+(tsx)",
      "!<rootDir>/src/**/*.index.+(tsx)"
    ],
    "coverageReporters": [
      "text",
      "text-summary"
    ]
  }
}
```

**Comment by ArtiomTr** [comment]
@grahammcculloch,

Sorry, I just now realized how vague this issue is. This issue is not about *parsing* jest configuration, it is about *taking threshold information from the jest configuration*, because action should show clear message, when threshold values are not met.

This action don't use any jest configuration to actually *run* tests, it simply runs the script, which is specified as `test-script` input ([here is the docs link](https://github.com/ArtiomTr/jest-coverage-report-action#customizing-test-script)). So if jest not takes information from `package.json` file, it is most likely that something is wrong with your `test-script` option.

**Comment by MarcosRava** [comment]
+1 
 I'm trying to use this action in a NestJS project , all jest configuration is in package.json

**Comment by simplewepro** [comment]
bump +1 for CRA
