### ISSUE TITLE
Action failing if PR raised from a Fork repository

### ISSUE THREAD

**Issue by ssurana2** [ArtiomTr/jest-coverage-report-action#256]
### Describe a bug
When a PR created from a forked repository is used for running the [jest-coverage-report-action](https://github.com/ArtiomTr/jest-coverage-report-action), the [jest-coverage-report-action](https://github.com/ArtiomTr/jest-coverage-report-action) is failing with the below error.

```
Begin switching back to original branch...
/usr/bin/git fetch --all --depth=1
Fetching origin
/usr/bin/git checkout -f inventoryManager
error: pathspec 'inventoryManager' did not match any file(s) known to git
Switching back to original branch failed
Error: Error: The process '/usr/bin/git' failed with exit code 1
Error: The process '/usr/bin/git' failed with exit code 1
    at jp._setResult (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:10:17263)
    at jp.CheckComplete (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:10:16853)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ArtiomTr/jest-coverage-report-action/v2/dist/index.js:10:15846)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)
```

### Expected behavior
Should checkout to the forked branch.

### Details

-   Action version: V2
-   OS, where your action is running (windows, linux): ubuntu-latest (github action)
-   <details>
     <summary>action.yml file</summary>
     
        name: 'Jest coverage report'
        
        on: [pull_request]
        
        jobs:
          jest_coverage_report:
            name: 'Jest coverage report'
            runs-on: ubuntu-latest
            steps:
              - name: Checkout the code
                uses: actions/checkout@v2
              - name: npm install
                run: npm ci
              - name: Coverage PR comment
                uses: ArtiomTr/jest-coverage-report-action@v2
                with:
                  annotations: coverage
    </details>

-   <details><summary>Screenshots</summary>
        <img width="911" alt="image" src="https://user-images.githubusercontent.com/10023250/161733118-ad79441f-6c6c-4630-ab66-bdfc924a6b24.png">
    </details>

**Comment by ArtiomTr** [comment]
Hello @ssurana2 :wave:,

Currently, forks are not supported.
