### ISSUE TITLE
Generate truncated report if limit 65535 reached

### ISSUE THREAD

**Issue by MisterJimson** [ArtiomTr/jest-coverage-report-action#262]
### Describe a bug

Using the action, seeing failures in Github actions logs.

### Expected behavior

API calls to Github should succeed and action should succesfully execute.

### Details

-   Action version: v2 (SHA:6f1418344ffb25717bf09a95cff68f9fa4c3bdad)
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

```yml
      - name: 🐛 Run tests
        uses: actions/ArtiomTr_jest-coverage-report-action@v2
        with:
          test-script: npm run test:ci
```

    </details>

-   <details><summary>Screenshots</summary>

        

        

    </details>

### Additional context

```
Begin failed tests' annotations publication...
Failed tests' annotations publication failed
Error: HttpError: Invalid request.

Only 65535 characters are allowed; 76633 were supplied.
HttpError: Invalid request.

Only 65535 characters are allowed; 76633 were supplied.
    at /runner/_work/_actions/actions/ArtiomTr_jest-coverage-report-action/v2/dist/index.js:2:329684
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /runner/_work/_actions/actions/ArtiomTr_jest-coverage-report-action/v2/dist/index.js:52:1897
    at async Ge (/runner/_work/_actions/actions/ArtiomTr_jest-coverage-report-action/v2/dist/index.js:51:156)
    at async Cw (/runner/_work/_actions/actions/ArtiomTr_jest-coverage-report-action/v2/dist/index.js:52:1762)
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```

**Comment by ArtiomTr** [comment]
Hello @MisterJimson :wave:,

That is GitHub's limitation - comments could have only 65535 characters. But I think the action could notify the user if the too long report was generated, and some detailed information was hidden.

**Comment by MisterJimson** [comment]
Maybe a way to have the report success but trimmed would be nice

**Comment by maciejtutak** [comment]
Hello!
I'm encountering a similar problem with the character limit, but it looks like mine is happening at a different stage. 

```
Test results written to: report.json
Done in 299.70s.
Running tests ended
Begin collecting coverage...
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish failed
Error: HttpError: Validation Failed: {"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
Error: Jest coverage report action failed
Error: Process completed with exit code 1.
```

I think I can code a simple fix that would check if the generated report length (with the title/footer template) is longer than the allowed limit, truncate it with some safe margin (say 1k characters) and prepend a warning message saying the report body was too long. 

Does this solution make sense?

**Comment by ArtiomTr** [comment]
Hello @maciejtutak :wave:,

I think report truncation will break the overall report structure and will look bad. In my opinion, if the report is too long, the details (2 spoilers - one with newly covered files and another with files with decreased coverage) should be omitted. Like this:
![Coverage comment example 1](https://user-images.githubusercontent.com/44021713/171211956-b7bd2324-a10e-4e58-864e-51a5a634db18.png)
This would look nice. However, I think it would be better if the report could contain at least some coverage details, like this:
![image](https://user-images.githubusercontent.com/44021713/171213374-519dfbdc-04f7-47dd-9493-114d1a744348.png)
I'd love to see your fix - this repository is always open for new contributors. You can pick one of these solutions (the first is a bit easier to code), or propose your own, as long as it follows the structure:
1. Title.
2. Errors (if there are any)
3. Overall coverage information (table).
4. Coverage details (not very important information, could be omitted)
5. Test execution result
6. Failed test output (also quite not important information, could be omitted).
7. Tool name ("Report generated by ..." string)
