### ISSUE TITLE
Requesting compatibility with Jest 28

### ISSUE THREAD

**Issue by pc-mwong** [ArtiomTr/jest-coverage-report-action#283]
I'm not 100% sure its related to Jest 28. It's hard to tell from these screenshots. 

I want to generate code coverage reports in JSON format with Jest 28 and use the `jest-coverage-report-action` with those reports. 

I tried to do that here and received this issue which could possibly be related to fact i'm using Jest 28. I know for a fact that the JSON code coverage report object has a different structure than jest 25 and possible 26 and 27.  The first property total has a new property called "branchesTrue"

<img width="859" alt="Screen Shot 2022-06-08 at 12 35 01 PM" src="https://user-images.githubusercontent.com/53789981/172702202-4cfdac45-8747-49ec-88a8-c0b64f112a05.png">

**Comment by ArtiomTr** [comment]
Hello @pc-mwong :wave:,

I've tried to generate a report with jest 28, and it looks like that report structure hasn't changed. Could you please attach your "report.json" file, so I can see where is the issue? Also, I've recently described some solutions for another problem, that looks similar to yours https://github.com/ArtiomTr/jest-coverage-report-action/issues/268#issuecomment-1148504250.

**Comment by pc-mwong** [comment]
> Hello @pc-mwong 👋,
> 
> I've tried to generate a report with jest 28, and it looks like that report structure hasn't changed. Could you please attach your "report.json" file, so I can see where is the issue? Also, I've recently described some solutions for another problem, that looks similar to yours [#268 (comment)](https://github.com/ArtiomTr/jest-coverage-report-action/issues/268#issuecomment-1148504250).

Yes, for security purposes heres a modified data version, but it's the same structure. Notice how the first report for coverage `"total"` has a new property `"branchesTrue"`.

```
{
    "total":{
       "lines":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "statements":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "functions":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "branches":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "branchesTrue":{
          "total":0,
          "covered":0,
          "skipped":0,
          "pct":100
       }
    },
    "/path-to-files/myComponent.js": {
       "lines":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "statements":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "functions":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
       "branches":{
          "total":10,
          "covered":1,
          "skipped":0,
          "pct":50
       },
     }


```

Maybe I'm a little confused here on whether its an issue with Jest 28. Maybe its with my Jest config but The reason why I am thinking its related is:

1. I added the GH action to my PR workflow and got that error I posted above.
2. I downloaded this repo and upgraded to Jest 28, ran your tests suites and got an error with `fileTransformer.js` telling me that it should not return a string and should return and object from now own with Jest 28 (see docs https://jestjs.io/docs/upgrading-to-jest28#transformer)

**Comment by pc-mwong** [comment]
> Hello @pc-mwong 👋,
> 
> I've tried to generate a report with jest 28, and it looks like that report structure hasn't changed. Could you please attach your "report.json" file, so I can see where is the issue? Also, I've recently described some solutions for another problem, that looks similar to yours [#268 (comment)](https://github.com/ArtiomTr/jest-coverage-report-action/issues/268#issuecomment-1148504250).

Oh, you're right! That seems to be the issue and thanks for the quick reply. I will try to re-adjust my jest config.

**Comment by ArtiomTr** [comment]
> 2. I downloaded this repo and upgraded to Jest 28, ran your tests suites and got an error with `fileTransformer.js` telling me that it should not return a string and should return and object from now own with Jest 28 (see docs https://jestjs.io/docs/upgrading-to-jest28#transformer)

Yes, this repository uses Jest 27, haven't migrated to the latest version yet. `fileTransformer.js` is just a utility file to run tests for this action - it is not included in the action's code, so it should not change the behaviour of this action.

**Comment by ArtiomTr** [comment]
@pc-mwong,

Jest supports javascript configuration, so your `jest.config.js` could look like this:
```js
import { readSync } from 'fs'

const fileContents = readSync('./someFile.json');

module.exports = {
    coverageThreshold: {
        global: {
            /* construct your thresholds dynamically */
        }
    }
}
```
[Coverage threshold option is described here](https://jestjs.io/docs/configuration#coveragethreshold-object).
About threshold option - it is working like intended, just like [standard jest coverage threshold](https://jestjs.io/docs/configuration#coveragethreshold-object). The feature of having "changedFilesThreshold" or "newFilesThreshold" was requested in another issue (#135), but I still don't have any ideas on how to implement it without adding unnecessary complexity to the action's behaviour.

I'm closing this issue because as I understood, the initial issue was resolved, and this action is still compatible with jest 28. However, feel free to open a new issue/discussion if you experience other problems with this action.
