### ISSUE TITLE
Annotation for changed files only

### ISSUE THREAD

**Issue by HarelM** [ArtiomTr/jest-coverage-report-action#308]
### Idea

I have tried adding this action to the repo I'm maintaining. This was super easy, but the repo coverage isn't great (that's why I want to introduce this).
When I use the default I get annotation of 11K violations, showing only the first 50.
While this might be useful for people that would like to make sure every PR gets better I would like to focus on the files that are being updated as part of this PR so that someone who changes a file can improve the code related to what he changed.
Maning I would like to see the annotation only on the file being changed, preferably, only on the lines that were changed and not even the entire file.

### Description

Add another type of annotation - `changed-files` to facilitate for the above.

### Alternatives

The only alternative I have right now is disable annotations, which results in a report that doesn't really help anyone as it is only "random" numbers that talk about coverage.

### Additional context

https://github.com/maplibre/maplibre-gl-js/pull/1527

**Comment by ArtiomTr** [comment]
Hello @HarelM :wave:,

Yeah, that's really nice idea. One person already proposed PR (#306), I'm currently working on it. Would this solution fit your needs? Or you want to see something different?

**Comment by HarelM** [comment]
Ah, didn't check the PRs, I searched only the issues.
This looks perfect according to the description there :-)

**Comment by ArtiomTr** [comment]
Closed by #306 
Available in version `v2.1.0` or just `v2`
