### ISSUE TITLE
Feature request: Custom GitHub Bot comments 

### ISSUE THREAD

**Issue by camelmasa** [ArtiomTr/jest-coverage-report-action#370]
## Idea

We are currently using the repository that forked this action in our private repository. The private repository is a monorepo, so this Actions will make multiple comments within a single pull request.
Therefore, it was necessary to narrow down the content in the comments to only the necessary information and remove the noisy parts.

Hide footer part
camelmasa@0f05710

Hide formatRunReport part
camelmasa@5497884

## Description

The corresponding part has been deleted in the forked repository, but it would be ideal if options could be specified with `with` in the GitHub workflow.

If you are okay with this idea, I would like to create a Pull Request.

**Comment by ArtiomTr** [comment]
Hello @camelmasa :wave:,

Yeah, that would be a nice feature for people who don't want to see test information in this report. I think we can add one more value for the `output` option https://github.com/ArtiomTr/jest-coverage-report-action/blob/f1a1382101d9b92b38e3df05c9ed89a834af97c8/action.yml#L50-L53
It could be something like `report-markdown-tiny` or `report-markdown-small`, something like this.

> If you are okay with this idea, I would like to create a Pull Request.

PRs are welcome, so feel free to implement this feature!

**Comment by camelmasa** [comment]
Sorry, I decided to solve my challenge by way of combine test coverages. 
Like this https://github.com/Shopify/cli/blob/main/.github/actions/run-and-save-test-coverage/action.yml.
