### ISSUE TITLE
ability to customize comment title

### ISSUE THREAD

**Issue by bmccann36** [ArtiomTr/jest-coverage-report-action#385]
### Idea

My feature request is mainly useful when running tests using gh actions matrix feature. I have a monorepo implemented with npm workspaces and I run this action on each workspace. It would be nice if each coverage comment could have a different heading (which I supply) so that I could tell which comment applies to which part of the codebase.

### Description

 I want to be able to customize the comment title VS only having the default "Coverage report" available

### Alternatives

- merge all coverage reports from each workspace in the monorepo into one report

### Additional context

I am open to working on this. I wanted to check if there is any appetite for it first.

**Comment by ArtiomTr** [comment]
Hey @bmccann36 :wave:,

Thank you for your request. This feature is already implemented, it is named `custom-title`: https://github.com/ArtiomTr/jest-coverage-report-action/blob/f1a1382101d9b92b38e3df05c9ed89a834af97c8/action.yml#L38-L40

Sorry, forgot to add documentation for it 😄

**Comment by bmccann36** [comment]
> Hey @bmccann36 👋,
> 
> Thank you for your request. This feature is already implemented, it is named `custom-title`:
> 
> https://github.com/ArtiomTr/jest-coverage-report-action/blob/f1a1382101d9b92b38e3df05c9ed89a834af97c8/action.yml#L38-L40
> 
> Sorry, forgot to add documentation for it 😄

oh nice! I see it now in the yaml spec file.
Would be great to add this to the documentation so folks know its available. I didn't realize that gh actions came with a manifest files which describes all the available inputs. Good to know

**Comment by ArtiomTr** [comment]
@bmccann36 thank you a lot for your support! If you'll need my help, feel free to ping me - I'll try to answer asap

**Comment by sheiman-pavlo** [comment]
Is it possible to add markdown support to custom title?  Having this in yaml:

```yaml
custom-title: "#### E2E Test Coverage :rotating_light:"
```

Produces this output: 
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/104133169/43035a6f-2bbb-440b-92c0-7a08b7f734bb)

**Comment by ArtiomTr** [comment]
hey @sheiman-pavlo :wave:,

Yes, this will work for now. However, this behavior will likely be removed in the next version.
