### ISSUE TITLE
Error: Coverage output file not found. (file "report.json" not found)

### ISSUE THREAD

**Issue by lixiaofa** [ArtiomTr/jest-coverage-report-action#396]
### Describe a bug
in the github actions , error

![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/23230215/fda08129-c840-4d01-92ed-b0502a79fcdd)

### Expected behavior

no error

### Details
This is my yaml file：
https://github.com/lixiaofa/fast-plus/blob/dev/.github/workflows/test-coverage.yml

**Comment by ArtiomTr** [comment]
Hello @lixiaofa :wave:,

As I can see, you're using `vitest`. This action supports only `jest`, although some people [were able to use it with vitest](https://github.com/ArtiomTr/jest-coverage-report-action/issues/244#issuecomment-1260555231).
