### ISSUE TITLE
Updated information hierarchy in github comment 

### ISSUE THREAD

**Issue by GeoffreyLong** [ArtiomTr/jest-coverage-report-action#403]
### Idea

The action should make it clearer that a failure was due to a failing test.

### Description

One of the engineers on my team reached out to me today because the thought there was an error in the action itself, and not just a simple failing test. The issue is that the fact that there is a failing test is buried in both the comment and in the console output.

This console output makes it seem like there was an error in the actual coverage generation. (I'm actually not sure if there actually was an error here or if this is as designed).
<img width="868" alt="Screenshot 2023-11-22 at 6 58 23 PM" src="https://github.com/ArtiomTr/jest-coverage-report-action/assets/5396938/d0df4d4f-8476-468c-8ba1-aa822efe23df">

And the main comment says "❌ An unexpected error occurred. For more details, check console" at the top level instead of saying "a test failed". The test failure information is at the bottom, almost like a footnote in the overall comment when it's actually the most important thing.
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/5396938/14303387-54c0-4c75-af01-ab9702bb6926)

### Alternatives

Ability to hide the failure messages in the comment.

### Additional context

None

**Comment by ArtiomTr** [comment]
Fixed in `v2.3.0`
