### ISSUE TITLE
Error in step "Begin coverage annotations publication"

### ISSUE THREAD

**Issue by matheuzsrlog** [ArtiomTr/jest-coverage-report-action#411]
### Describe a bug
I have a problem with the step "Begin coverage annotations publication". It gives the error: 
`Error: HttpError: Validation Failed: {"resource":"CheckRun","code":"invalid","field":"annotations"}.`

I don't know if it could be a permission error. More is happening.
(I decided to open the issue, after all I didn't change anything about permissions beforehand)

**Below I left a print with the output of the action**

### Details

-   Action version: ArtiomTr/jest-coverage-report-action@df2b025553c31d68f84be6337843e277e2576844
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

        ```yml
        - uses: ArtiomTr/jest-coverage-report-action@df2b025553c31d68f84be6337843e277e2576844
        ```

    </details>

-   <details><summary>Screenshots</summary>
       ![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/77068076/44d2b3c2-2c53-4a98-a2e4-0395112a0c7b)
        

    </details>

**Comment by ArtiomTr** [comment]
Hello @matheuzsrlog,

Are you running this action in public repo? It would be easier if I could check logs by myself. Also, if it is possible, could you please upload your `report.json` file here?

**Comment by matheuzsrlog** [comment]
No. My repository is not a public. :/
And, I don't have my artefact report.json, I think that is can to be also, my cache limit.
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/77068076/51bd68dc-4f23-4be8-99f0-3d2f50470405)

**Comment by matheuzsrlog** [comment]
When checking my artifacts I have these related to coverage. But not report.json (this could also be the problem, I'm checking)

**Comment by ArtiomTr** [comment]
`report.json` is not stored as artifact, so that's not the problem.

Can you please run 
```
npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
```
And post `report.json` file here or send an email to `maintainers@covbot.dev`?

**Comment by matheuzsrlog** [comment]
> maintainers@covbot.dev

Do you receive my email? I am think that no sended.

**Comment by ArtiomTr** [comment]
Yes, thank you, will look into it

**Comment by ArtiomTr** [comment]
I have 0 clue why this is happening, tried some random fix, can you please check if it works? Just modify your `action.yaml` like so:
```yaml
- uses: ArtiomTr/jest-coverage-report-action@Invalid-annotations-schema
```

**Comment by matheuzsrlog** [comment]
Thank you, I am go try it!

**Comment by matheuzsrlog** [comment]
Good job, it work out! Thank very much

**Comment by ArtiomTr** [comment]
Seems like annotations array cannot be empty. I will do another fix, so it covers both this issue and #383

**Comment by ArtiomTr** [comment]
Added other fix, but it should do almost the same as previous one. Could you please check, if `v2.2.9` works for you?

**Comment by matheuzsrlog** [comment]
> Added other fix, but it should do almost the same as previous one. Could you please check, if `v2.2.9` works for you?

Only change for?
`- uses: ArtiomTr/jest-coverage-report-action@v2.2.9`

**Comment by ArtiomTr** [comment]
Yep

**Comment by matheuzsrlog** [comment]
All right!! 
Thanks man, good one for you!
![image](https://github.com/ArtiomTr/jest-coverage-report-action/assets/77068076/5625ced3-7f6e-48df-a57d-478e40054512)
