### ISSUE TITLE
HttpError: The diff exceeded the maximum number of files (300).

### ISSUE THREAD

**Issue by aromko** [ArtiomTr/jest-coverage-report-action#430]
### Describe a bug
Hey,

I've made a prettier change which affects ~420 files. Now the coverage report fails with error:

Error: HttpError: Sorry, the diff exceeded the maximum number of files (300). Consider using 'List pull requests files' API or locally cloning the repository instead.: {"resource":"PullRequest","field":"diff","code":"too_large"}

How can I fix this?

Thanks in advance

### Expected behavior

Job shouldn't fail.

### Details

-   Action version: ArtiomTr/jest-coverage-report-action@v2

**Comment by morganney** [comment]
Maybe add an option to not fail the run if more than 300 files.
