### ISSUE TITLE
Coverage run not respecting yarn.lock

### ISSUE THREAD

**Issue by debajitr** [ArtiomTr/jest-coverage-report-action#65]
Hi, wanted to start by thanking you for this awesome action, its great 👍🏻

Issue: We use yarn.lock in our codebase to lock dependencies in place, due to which our action for test passed, but this action for coverage failed as it pulled in the latest package hence failing our dependent snapshots.

Can we please make some changes so that this action respects the yarn.lock, OR maybe have configuration in a way where we as a user after checkout, do the regular node setup, and yarn install, and this package only runs coverage. Thoughts, suggestions?

**Comment by ArtiomTr** [comment]
Hi @debajitr!

It would be great if action could handle both the `npm` and `yarn` package managers! I think there should be a `package-manager` option to let the user choose which package manager to use.

Our repository is open to new users, so if you'd like to contribute, I'll be glad!
