### ISSUE TITLE
Support multiple instances in one project

### ISSUE THREAD

**Issue by oxc** [ArtiomTr/jest-coverage-report-action#71]
We have two separate package.json in our project (frontend and backend), and I would like to run code coverage for both for each Pull Request.

The minimum requirement would be a configurable name that is included in the comment tag, so that the two instances don't override each other's comment.

**Comment by oxc** [comment]
I just discovered the 'dir' parameter in the code. I'm not sure why I thought this didn't work.

**Comment by ArtiomTr** [comment]
Hello @oxc,

Yes, we've already implemented this functionality, but currently this feature is not released. If you want to try it, use `@master` version, and, run this action twice but with 2 different `working_directory` props. More information about `@master` version could be found [here](https://github.com/ArtiomTr/jest-coverage-report-action/issues/32#issuecomment-855943136)

**Comment by oxc** [comment]
Yeah, just found the commit :) Thanks!

**Comment by sleiss** [comment]
Hey @ArtiomTr,

has this change already been included in the latest releases?

**Comment by ArtiomTr** [comment]
Hello @sleiss,

Yes, this feature is available from `v1.2` I think, but I recommend to use latest `v2.0-rc.4` release 😄 

Also, a new version `v2.0-rc.5` is coming soon, which will make it possible to create multiple reports even in the same directory using different scripts. See #172 for more details.
