### ISSUE TITLE
Use `Jest`'s `coverageThreshold` instead of `threshold` option

### ISSUE THREAD

**Issue by taschetto** [ArtiomTr/jest-coverage-report-action#82]
`Jest` has a `coverageThreshold` configuration. We could leverage this instead of using a fixed `threshold` option.

See: https://jestjs.io/docs/configuration#coveragethreshold-object

**Comment by ArtiomTr** [comment]
Cool idea! Maybe you would like to implement it?

**Comment by taschetto** [comment]
I'll try. :)
