### ISSUE TITLE
Typo in input parameter - github-token

### ISSUE THREAD

**Issue by mrchief** [ArtiomTr/jest-coverage-report-action#86]
Docs say to use `github-token` but the action expects `github_token` 
![image](https://user-images.githubusercontent.com/781818/123457144-9de6ac00-d5b1-11eb-89ef-caed9f295c3f.png)

**Comment by mrchief** [comment]
I think the confusion stems from this 
![image](https://user-images.githubusercontent.com/781818/123471110-4bae8680-d5c3-11eb-8369-eaa406fbdfa8.png)

Using the latest rc version, dash `github-token` works

**Comment by ArtiomTr** [comment]
Oh yeah, thank you! Forgot to update, just configuration example in `README.md` file is for the latest version. I'll fix that!
